### ISSUE TITLE
ncon???

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/JSOSuite.jl#22]
Why is the `ncon` parameter necessary in `fmincon`? It's just the length of `c`, isn't it?

**Comment by abelsiqueira** [comment]
In function where the is `lcon` or `ucon`, `ncon` can be computed, but `c` is a function, so we would have to make one function evaluation to find out `ncon`.

**Comment by dpo** [comment]
Ok, nevermind.
