### ISSUE TITLE
Error doc deployment

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/JSOSuite.jl#36]
@abelsiqueira @dpo I am suspecting there is an error with the deploy key for the docs.

Here is the error
```
ERROR: Permission to JuliaSmoothOptimizers/JSOSuite.jl.git denied to deploy key
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

_Originally posted by @tmigot in https://github.com/JuliaSmoothOptimizers/JSOSuite.jl/issues/35#issuecomment-1222307445_

**Comment by dpo** [comment]
There is no deploy key, so that would be why. Let me add one.

**Comment by dpo** [comment]
Let me know if it works now.

**Comment by tmigot** [comment]
It works! Thanks!
